services:
  web:
    build: .
    command: /start-dev
    volumes:
      - .:/app
      - staticfiles:/app/staticfiles
      - media:/app/media
    ports:
      - "8000:8000"
    env_file:
      - .env.dev
    depends_on:
      - redis

  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"

  celery_worker:
    build: .
    command: /start-celeryworker
    volumes:
      - .:/app
    env_file:
      - .env.dev
    depends_on:
      - redis
      - web

  celery_beat:
    build: .
    command: /start-celerybeat
    volumes:
      - .:/app
    env_file:
      - .env.dev
    depends_on:
      - redis
      - web

volumes:
  staticfiles:
  media: