# docker compose for development
x-common-django: &common-django
  build: .
  volumes:
    - .:/app
    - staticfiles:/app/staticfiles
    - media:/app/media
  env_file:
    - .env
  depends_on:
    - redis

services:
  web:
    <<: *common-django
    command: /start-dev
    ports:
      - "8000:8000"

  redis:
    image: redis:7-alpine
    volumes:
      - redis_data:/data
    ports:
      - "6379:6379"

  celery_worker:
    <<: *common-django
    command: /start-celeryworker
    depends_on:
      - redis
      - web

  celery_beat:
    <<: *common-django
    command: /start-celerybeat
    depends_on:
      - redis
      - web

volumes:
  redis_data:
  staticfiles:
  media: