# Generated by Django 5.2.7 on 2025-10-27 22:27

import core.fields
import core.utils
import imagekit.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '__latest__'),
        ('contenttypes', '__latest__'),
    ]


    operations = [
        migrations.CreateModel(
            name="User",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("password", models.CharField(max_length=128, verbose_name="password")),
                (
                    "last_login",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="last login"
                    ),
                ),
                (
                    "username",
                    models.CharField(
                        blank=True,
                        help_text="Opcional. 150 caracteres ou menos. Letras, dígitos e @/./+/-/_ apenas.",
                        max_length=150,
                        null=True,
                        unique=True,
                        verbose_name="username",
                    ),
                ),
                (
                    "full_name",
                    models.CharField(max_length=100, verbose_name="Nome Completo"),
                ),
                (
                    "email",
                    models.EmailField(
                        max_length=255, unique=True, verbose_name="email address"
                    ),
                ),
                (
                    "cpf",
                    core.fields.CPFField(
                        max_length=14, unique=True, verbose_name="CPF"
                    ),
                ),
                (
                    "profile_photo",
                    imagekit.models.fields.ProcessedImageField(
                        blank=True,
                        null=True,
                        upload_to=core.utils.FormatStringFileUpload(
                            "users/profile/{instance.id}/{filename}"
                        ),
                        verbose_name="Foto de Perfil do Usuário",
                    ),
                ),
                (
                    "role",
                    models.CharField(
                        choices=[
                            ("Superadmin", "Superadmin"),
                            ("Admin", "Administrador"),
                            ("Comum", "Comum"),
                        ],
                        default="Comum",
                        max_length=30,
                        verbose_name="Perfil do Usuário",
                    ),
                ),
            ],
            options={
                "verbose_name": "Usuário",
                "verbose_name_plural": "Usuários",
            },
        ),
    ]
