name: CI/CD Pipeline

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    
    services:
      postgres:
        image: postgres:13
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
          POSTGRES_DB: test_db
        ports:
          - 5432:5432
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
      
      redis:
        image: redis:7-alpine
        ports:
          - 6379:6379

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.12'
        cache: 'pip'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Run migrations and tests
      env:
        DEBUG: "False"
        SECRET_KEY: test-secret-key-for-ci-cd-pipeline
        POSTGRES_DB: test_db
        POSTGRES_USER: postgres
        POSTGRES_PASSWORD: postgres
        POSTGRES_HOST: localhost
        POSTGRES_PORT: 5432
        CELERY_BROKER_URL: redis://localhost:6379/0
        CELERY_RESULT_BACKEND: redis://localhost:6379/0
      run: |
        python manage.py migrate --noinput
        python manage.py test
        python manage.py check --deploy

  deploy:
    if: github.event_name == 'push' || (github.event_name == 'pull_request' && github.event.pull_request.merged == true)
    runs-on: ubuntu-latest
    needs: test
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Deploy to production server
      uses: appleboy/ssh-action@v1.0.3
      with:
        host: ${{ secrets.SERVER_HOST }}
        username: ${{ secrets.SERVER_USERNAME }}
        key: ${{ secrets.SERVER_SSH_KEY }}
        script: |
          set -e
          
          echo "🚀 INICIANDO DEPLOY AUTOMÁTICO..."
          
          cd /opt/django-bootstrap
          
          # Pull do código mais recente
          echo "📥 Atualizando código..."
          git pull origin main
          
          # Build das imagens usando arquivo de produção
          echo "🐳 Build das imagens Docker (produção)..."
          docker compose -f docker-compose.prd.yml build --no-cache
          
          # Parar e recriar os containers
          echo "🔄 Reiniciando containers..."
          docker compose -f docker-compose.prd.yml down
          docker compose -f docker-compose.prd.yml up -d
          
          # Aguardar serviços iniciarem
          echo "⏳ Aguardando serviços iniciarem..."
          sleep 10
          
          # Executar migrações
          echo "🗃️ Executando migrações..."
          docker compose -f docker-compose.prd.yml exec -T web python manage.py migrate --noinput
          
          # Coletar static files
          echo "📦 Coletando arquivos estáticos..."
          docker compose -f docker-compose.prd.yml exec -T web python manage.py collectstatic --noinput --clear
          
          # Verificar se os serviços estão rodando
          echo "✅ Verificando serviços..."
          docker compose -f docker-compose.prd.yml ps
          
          # Verificar logs recentes
          echo "📋 Logs recentes do serviço web:"
          docker compose -f docker-compose.prd.yml logs --tail=20 web
          
          echo "🎉 DEPLOY CONCLUÍDO COM SUCESSO!"
          echo "🌐 Acesse: http://${{ secrets.SERVER_HOST }}"
