name: CI/CD Pipeline

on:
  push:
    branches: [ main ]
  pull_request:
    types: [ closed ]
    branches: [ main ]

jobs:
  test:
    if: github.event_name == 'pull_request' && github.event.action == 'closed' && github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    
    services:
      postgres:
        image: postgres:13
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
          POSTGRES_DB: test_db
        ports:
          - 5432:5432
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
      
      redis:
        image: redis:7-alpine
        ports:
          - 6379:6379

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.12'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Run migrations and tests
      env:
        DEBUG: 0
        SECRET_KEY: test-secret-key-for-ci-cd
        DATABASE_URL: postgresql://postgres:postgres@localhost:5432/test_db
        CELERY_BROKER_URL: redis://localhost:6379/0
        CELERY_RESULT_BACKEND: redis://localhost:6379/0
      run: |
        python manage.py migrate
        python manage.py test
        python manage.py check --deploy

  deploy:
    if: github.event_name == 'push' || (github.event_name == 'pull_request' && github.event.action == 'closed' && github.event.pull_request.merged == true)
    runs-on: ubuntu-latest
    needs: test
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Deploy to production server
      uses: appleboy/ssh-action@v1.0.3
      with:
        host: ${{ secrets.SERVER_HOST }}
        username: ${{ secrets.SERVER_USERNAME }}
        key: ${{ secrets.SERVER_SSH_KEY }}
        script: |
          echo "🚀 INICIANDO DEPLOY AUTOMÁTICO..."
          
          cd /opt/django-bootstrap
          
          # Pull do código mais recente
          echo "📥 Atualizando código..."
          git pull origin main
          
          # Build das imagens localmente
          echo "🐳 Build das imagens Docker..."
          docker-compose build --no-cache
          
          # Parar e recriar os containers
          echo "🔄 Reiniciando containers..."
          docker-compose down
          docker-compose up -d
          
          # Executar migrações
          echo "🗃️ Executando migrações..."
          docker-compose exec -T web python manage.py migrate --noinput
          
          # Coletar static files
          echo "📦 Coletando arquivos estáticos..."
          docker-compose exec -T web python manage.py collectstatic --noinput
          
          # Verificar se os serviços estão rodando
          echo "✅ Verificando serviços..."
          docker-compose ps
          
          echo "🎉 DEPLOY CONCLUÍDO COM SUCESSO!"
          echo "🌐 Acesse: http://${{ secrets.SERVER_HOST }}"